name: "Hello world"
description: "My first real app!"
version: "1.0.0"
slug: "hello_world"
init: false
ingress: true
ingress_ports: 8080
panel_icon: "mdi:alarm"
panel_title: "Przypomnienia"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: null
