name: "Reminder"
description: "Custom reminder service"
version: "1.0.0"
slug: "reminder"
init: false
ingress: true
ingress_port: 8080
panel_icon: "mdi:alarm"
panel_title: "Przypomnienia"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

